language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get -qq install libcairo2-dev libcairo-gobject2 gtk-doc-tools

before_script:
    - ./autogen.sh && mkdir -p _build && cd _build

script:
    - ../configure && make && make check

after_script:
    - cd ..

notifications:
    email:
        recipients:
            - ntd@entidi.it
