branches:
    only:
        - master

language: c

compiler:
    - clang
    - gcc

env:
    - GTK=gtk2
    - GTK=gtk3

before_install:
    - sudo apt-get update -qq

install:
    - sudo pip install cpp-coveralls
    - sudo apt-get -qq install libcairo2-dev libcairo-gobject2 libgtk2.0-dev libgtk-3-dev gtk-doc-tools

before_script:
    - ./autogen.sh --verbose && mkdir -p _build && cd _build

script:
    - ../configure --enable-gcov --with-gtk=$GTK && make && make V=1 check

after_success:
    - if [ "$CC" = "gcc" ]; then coveralls -r .. -x c -e demo -e src/tests -e src/cpml/tests -e src/adg/tests -e _build/src/adg/adg-marshal.c --gcov-options '\-lp'; fi

after_script:
    - cd ..

notifications:
    email:
        recipients:
            - ntd@entidi.it
