language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo pip install cpp-coveralls
    - sudo apt-get -qq install libcairo2-dev libcairo-gobject2 gtk-doc-tools

before_script:
    - ./autogen.sh --verbose && mkdir -p _build && cd _build

script:
    - ../configure --enable-gcov && make && make check

after_success:
    - if [ "$CC" = "gcc" ]; then coveralls -e demo -e src/cpml/tests -e src/adg/tests; fi

after_script:
    - cd ..

notifications:
    email:
        recipients:
            - ntd@entidi.it
